# Generated by Django 2.1.7 on 2019-03-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('num_labs', models.IntegerField(default=0)),
                ('instructor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=-1)),
                ('name', models.CharField(default='DEFAULT', max_length=50)),
                ('isLoggedOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_assign.Person')),
            ],
            bases=('ta_assign.person',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_assign.Person')),
            ],
            bases=('ta_assign.person',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_assign.Person')),
            ],
            bases=('ta_assign.person',),
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ta_assign.Person')),
            ],
            bases=('ta_assign.person',),
        ),
        migrations.AddField(
            model_name='course',
            name='tee_ays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.TA'),
        ),
    ]
