# Generated by Django 2.1.7 on 2019-04-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcourse',
            name='instructor',
            field=models.CharField(default='no Instructor', max_length=50),
        ),
        migrations.AlterField(
            model_name='modelperson',
            name='phone',
            field=models.IntegerField(default='000.000.0000', max_length=12),
        ),
    ]
