# Generated by Django 2.1.7 on 2019-03-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcourse',
            name='tee_ays',
        ),
    ]
