# Generated by Django 2.1.7 on 2019-03-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_assign', '0002_remove_modelcourse_tee_ays'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTACourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.ModelTA')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_assign.ModelCourse')),
            ],
        ),
    ]
